### ISSUE TITLE
Win10连接失效

### ISSUE THREAD

**Issue by ZeroSkman** [fhyuncai/Arknights-Anti-addiction#1]
如标题

**Comment by fhyuncai** [comment]
win10作服务端还是？麻烦补充详细

**Comment by ZeroSkman** [comment]
那个下载的链接404了，大佬有更详细的教程吗，看的我有点懵

**Comment by ZeroSkman** [comment]
我用Termux运行后进方舟显示获取网络配置失败错误号0

**Comment by fhyuncai** [comment]
链接已修复 教程在写了（

**Comment by fhyuncai** [comment]
> 我用Termux运行后进方舟显示获取网络配置失败错误号0

方便截个图吗

**Comment by ZeroSkman** [comment]
好的谢谢大佬

**Comment by ZeroSkman** [comment]
![image](https://user-images.githubusercontent.com/62535487/119115657-ff1edb00-ba59-11eb-907f-4abe1dabee16.png)
![image](https://user-images.githubusercontent.com/62535487/119115664-00e89e80-ba5a-11eb-8e0d-1bdce0ca4d88.png)
大佬这个文件似乎也有问题，之前配置错误0应该是没用这个bat

**Comment by fhyuncai** [comment]
右键编辑bat文件，删掉下面的代码试试
```
for /f "tokens=4" %%a in ('route print^|findstr 0.0.0.0.*0.0.0.0') do (
    set ip=%%a
)
echo 主机名：%ip%
```

**Comment by ZeroSkman** [comment]
还是不行

**Comment by ZeroSkman** [comment]
要不你加我QQ吧1369637417

**Comment by fhyuncai** [comment]
修好了 重新下载压缩包就行了

**Comment by ZeroSkman** [comment]
现在怎么用啊运行bat后显示的ip和端口上手机链接wifi改吗？模拟器能不能用

**Comment by fhyuncai** [comment]
> 现在怎么用啊运行bat后显示的ip和端口上手机链接wifi改吗？模拟器能不能用

都可以，模拟器可能更方便些

到 Google Play 下载 HTTP Proxy Client ，输入框内输入 服务端 `IP:服务端端口` ，如 `192.168.1.101:10032` ， 点击 START 启用

**Comment by ZeroSkman** [comment]
ip 和端口都输bat的吗还是输入自己的，模拟器的话wifi要不要改桥接

**Comment by fhyuncai** [comment]
> ip 和端口都输bat的吗还是输入自己的，模拟器的话wifi要不要改桥接

bat的，不用改

**Comment by ZeroSkman** [comment]
大佬我去试了一下还是错误0

**Comment by ZeroSkman** [comment]
用Termux运行curl https://raw.githubusercontents.com/fhyuncai/Arknights-Anti-addiction/main/install_termux.sh | bash 后显示下载失败挂梯子也试了

**Comment by ZeroSkman** [comment]
现在又下载好了不过还是错误0
![Uploading Screenshot_20210521-180426.jpg…]()

**Comment by ZeroSkman** [comment]
![Screenshot_20210521-180426](https://user-images.githubusercontent.com/62535487/119120909-6428ff80-ba5f-11eb-80b2-b07f44f1b496.jpg)

**Comment by fhyuncai** [comment]
> 大佬我去试了一下还是错误0

我这边用 Mumu 可以啊，模拟器是 Android 6 还是 7

**Comment by ZeroSkman** [comment]
我用的手机安卓10

**Comment by ZeroSkman** [comment]
我用mumu试下

**Comment by fhyuncai** [comment]
> 我用的手机安卓10

手机要额外安装证书，需要 root

**Comment by ZeroSkman** [comment]
mitmproxy的证书吗？我手机已经root刷面具了

**Comment by fhyuncai** [comment]
https://www.cnblogs.com/oboth-zl/p/13818981.html
